food/urls.py
from . import views 
from django.urls import path

app_name = 'food'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:item_id>/', views.detail, name='detail'),  # Corrected line
    path('item/', views.item, name='item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
]

food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name




    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()

food/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Item
from django.template import loader

def index(request):
    item_list = Item.objects.all()  # Fetch all items from the database
    template = loader.get_template('food/index.html')
    context = {
        'item_list': item_list
    }
    return HttpResponse(template.render(context, request))

def item(request):
    return HttpResponse('<h1>This is an item view</h1>')

def detail(request, item_id):
    item = get_object_or_404(Item, pk=item_id)  # Corrected line
    context = {
        'item': item,
    }
    return render(request, 'food/detail.html', context)

food/templates/food/detail.html
<h1> {{ item.item_name }} </h1>
<h2> {{ item.item_desc }} </h2>
<h3> {{ item.item_price }} </h3>

food/templates/food/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}"></head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<body>
<nav  class = "navbar navbar-dark  bg-dark">  
    <a href="# " class="navbar-brand">Food App</a> 

    <div class="navbar">
        <a class="nav-item" href="#" nav-link>Add item</a> 
        <a class="nav-item " href="#" nav-link>Delete item </a>
         <a class="nav-item " href="#" nav-link> View item</a>

    </div>
</nav>



    {% for item in item_list %}
    <ul>
        <li>
            <a href="{% url 'food:detail' item.id %}"> {{ item.id }} --{{item.item_name }}</a>
        </li>
    </ul>

{% endfor %}
</body>
</html>